FROM mcr.microsoft.com/playwright:bionic

# RUN apk add -U \
#   python3\
#   make\
#   alpine-sdk

# RUN apk add --no-cache \
#   chromium \
#   firefox \
#   nss \
#   freetype \
#   harfbuzz \
#   ca-certificates \
#   ttf-freefont \
#   nodejs \
#   yarn
