FROM node:16-alpine3.16

RUN apk add -U \
    python3\
    make\
    alpine-sdk

RUN adduser --gecos "" --disabled-password jenkins \
    && echo "jenkins:jenkins" | chpasswd \
    && chmod -R jenkins:jenkins /home/jenkins \
    && mkdir /home/jenkins/playwright

USER jenkins

